const Sdata = [
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215642/avatar/ayurvedic_paifbk.jpg",
        title:"Ayurveda",
        price:"500",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215643/avatar/cardiology-icon_yvjzfp.jpg",
        title:"Cardiology",
        price:"2500",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215567/avatar/dermatology_mbtyah.png",
        title:"Dermatology",
        price:"1500",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215617/avatar/gynecology-icon_yijgwg.png",
        title:"Gynecology",
        price:"600",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215667/avatar/ophthalmology_g2bynq.jpg",
        title:"Ophthalmology",
        price:"500",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215667/avatar/orthopedic-icon_f39e23.png",
        title:"Orthopedic",
        price:"800",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215667/avatar/padiatrics_kws3h6.png",
        title:"Padiatrics",
        price:"500",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215681/avatar/psychiatry_pqoszd.png",
        title:"Psychiatry",
        price:"540",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215681/avatar/sexology_mvxfko.png",
        title:"Sexology",
        price:"550",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215686/avatar/stethoscope-icon_y4sh6o.png",
        title:"General Physician",
        price:"400",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215683/avatar/stomach-icon_jnlh7p.png",
        title:"Gastroenterologist",
        price:"550",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215688/avatar/surgeon_e9xojo.png",
        title:"Surgeon",
        price:"1500",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215689/avatar/teeth-icon_ihwftz.png",
        title:"Dentist",
        price:"350",
        link:"#",
    },
    {
        imgsrc:"https://res.cloudinary.com/dgejdmzwv/image/upload/v1637215694/avatar/uro-icon_xfskaj.png",
        title:"Urology",
        price:"550",
        link:"#",
    },

];

export default Sdata;