const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    // GET_MEDICAL_PROFILE:'GET_MEDICAL_PROFILE'
}

export default ACTIONS
